# Generated by Django 6.0.4 on 2026-04-23 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateField()),
                ('horario_evento', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('is_pago', models.BooleanField(default=False, verbose_name='Evento Pago?')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('carga_horaria', models.IntegerField(default=0, help_text='Horas para sair no certificado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventos.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gratis', 'Gratuito'), ('pendente', 'Aguardando Pagamento'), ('aprovado', 'Pagamento Aprovado'), ('recusado', 'Pagamento Recusado')], default='gratis', max_length=20)),
                ('id_transacao_mp', models.CharField(blank=True, help_text='ID gerado pelo Mercado Pago', max_length=100, null=True)),
                ('link_pagamento', models.URLField(blank=True, null=True)),
                ('presenca_confirmada', models.BooleanField(default=False, help_text='Se marcado, o aluno pode emitir o certificado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
