# Generated by Django 6.0.4 on 2026-04-25 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='id_transacao_mp',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='codigo_ingresso',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_transacao_picpay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='presenca_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
