# Generated by Django 6.0.4 on 2026-04-25 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_inscricao_id_transacao_mp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='codigo_ingresso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
