# Generated by Django 6.0.4 on 2026-04-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_inscricao_codigo_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.IntegerField(default=0, help_text='Limite de vagas. Ex: 20 para minicursos. Deixe 0 para ilimitado (Palestras).'),
        ),
    ]
