# Generated by Django 6.0.4 on 2026-04-29 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_vagas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Ex: 10', unique=True)),
                ('ano', models.IntegerField()),
                ('titulo_tema', models.CharField(blank=True, max_length=200)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='edicoes/capas/')),
            ],
            options={
                'verbose_name': 'Edição',
                'verbose_name_plural': 'Edições',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='edicoes/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='eventos.edicao')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
            },
        ),
    ]
