# Generated by Django 6.0.4 on 2026-05-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_edicao_galeriafoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galeriafoto',
            options={},
        ),
        migrations.RemoveField(
            model_name='edicao',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='edicao',
            name='titulo_tema',
        ),
        migrations.AddField(
            model_name='edicao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='numero',
            field=models.CharField(help_text='Ex: Edição X, Edição IX', max_length=20),
        ),
        migrations.AlterField(
            model_name='galeriafoto',
            name='imagem',
            field=models.ImageField(upload_to='galeria/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='galeriafoto',
            name='legenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
