# Generated by Django 6.0.4 on 2026-04-27 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_alter_inscricao_codigo_ingresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote_escolhido', models.CharField(choices=[('palestras', 'Passaporte Palestras (R$ 20,00)'), ('minicurso', 'Minicurso Avulso (R$ 40,00)'), ('combo', 'Combo: Palestras + 1 Minicurso (R$ 50,00)')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('aprovado', 'Pagamento Aprovado'), ('recusado', 'Pagamento Recusado')], default='pendente', max_length=20)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('link_pagamento', models.URLField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('minicurso_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
