# Generated by Django 6.0.4 on 2026-04-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pacote_escolhido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pacote',
            field=models.CharField(choices=[('palestras', 'Todas as Palestras (R$ 50,00)'), ('minicurso', 'Apenas 1 Minicurso (R$ 50,00)'), ('combo', 'Combo: Todas as Palestras + 1 Minicurso (R$ 80,00)')], default='palestras', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_transacao',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
