# Generated by Django 6.0.4 on 2026-05-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_remove_pedido_pacote_escolhido_pedido_pacote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Lote 1, Lote 2, Último Lote', max_length=50)),
                ('preco_palestras', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Passaporte Palestras')),
                ('preco_minicurso', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Minicurso Avulso')),
                ('preco_combo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Combo (Palestras + 1 Minicurso)')),
                ('ativo', models.BooleanField(default=False, help_text='Marque para ativar este lote. Os outros serão desativados automaticamente.')),
            ],
            options={
                'verbose_name': 'Lote de Venda',
                'verbose_name_plural': 'Lotes de Venda',
            },
        ),
    ]
