# Generated by Django 6.0.4 on 2026-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_transacao_mp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qr_code_pix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
