# Generated by Django 6.0.4 on 2026-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cpf_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passaporte_palestras',
            field=models.BooleanField(default=False, help_text='Tem acesso livre a todas as palestras?'),
        ),
    ]
